<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Authors>Doctracker</Authors>
    <Company>Doctracker</Company>
    <Copyright>Copyright © 2026</Copyright>
  </PropertyGroup>
</Project>
